### ISSUE TITLE
Nova forma de conexão ao CEI

### ISSUE THREAD

**Issue by jonaspicpay** [gicornachini/bolsa#2]
É mais uma dica... Em vez de usar a url https://cei.b3.com.br/CEI_Responsivo/, pode usar essa url: https://ceiapp.b3.com.br/CEI_Responsivo/login.aspx.
Por hora, ela não possui o captcha...

Att

**Comment by gicornachini** [comment]
Obrigado @jonaspicpay pela sugestão! Testei aqui alterando as URL's para este subdomain e rolou. Gerei uma nova major release sem captcha resolver como obrigatório, mas caso seja adicionado o `recaptcha` neste subdomínio, conseguimos simplesmente passar uma implementação de `captcha resolver` que vai funcionar...
