### ISSUE TITLE
pip não consta versão

### ISSUE THREAD

**Issue by lclpedro** [gicornachini/bolsa#3]
A sua versão não consta nos repositórios do pypserver.. (última versão lá ta como 2.0.0) Se puder subir novamente! Abraços e vlw a iniciativa! ;)

**Comment by lclpedro** [comment]
Na vdd quem está quebrando o seu módulo é o aidns >= 2.0.1 a mesma encontra-se na 2.0.0

**Comment by gicornachini** [comment]
@lclpedro Obrigado pelo report. Verifiquei aqui, era um problema com a versão do `aiodns` registrada no [setup.py](https://github.com/gicornachini/bolsa/blob/master/setup.py#L14). Corrigi para a versão 2.0.0 e voltou a funcionar. Mandei a release da `2.0.2` corrigindo isso 🎉
